(cl:in-package ivactuator-msg)
(cl:export '(UISTEERANGLE-VAL
          UISTEERANGLE
          REALSTRTORQUE-VAL
          REALSTRTORQUE
          UISPEED-VAL
          UISPEED
          ESPACCEL-VAL
          ESPACCEL
          SHIFTLVLPOSITION-VAL
          SHIFTLVLPOSITION
          CURRENTDRVMODE-VAL
          CURRENTDRVMODE
          SYSSTATUS-VAL
          SYSSTATUS
          VEHICLESYSFAULT-VAL
          VEHICLESYSFAULT
          BATTERYVOLTAGE-VAL
          BATTERYVOLTAGE
          RESERVE1-VAL
          RESERVE1
          RESERVE2-VAL
          RESERVE2
          RESERVE3-VAL
          RESERVE3
          RESERVE4-VAL
          RESERVE4
          ISVALID-VAL
          ISVALID
))